[package]
name = "advent-of-code-2021"
version = "0.1.0"
authors = ["Edward Lee <edwardlee.259@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_more = "0.99.17"
itertools = "0.10.3"